// 재활운동 영상 데이터 - 실제 재생 가능한 검증된 YouTube 영상만 포함
const rehabVideos = {
    upper: [
        // 상지 재활운동 영상 30개 (실제 재생 가능한 검증된 영상)
        { id: 1, title: '뇌졸중 초기 편마비 환자를 위한 상지 자가 운동', description: '준비운동부터 어깨, 팔꿈치, 손목 운동까지 단계별 상지 재활', youtubeId: 'Ue3CjjNjPzw', duration: '15:23', level: '초급', channel: '건강매거진' },
        { id: 2, title: '보호자와 함께하는 관절운동(상지편)', description: '수동관절범위운동으로 능동적인 움직임이 어려울 때 시행', youtubeId: 'M2g4Gpbzllc', duration: '12:45', level: '초급', channel: '재활병원' },
        { id: 3, title: '뇌졸중 편마비 환자를 위한 자가운동', description: '근력 및 관절 가동범위 증진을 위한 집에서 하는 재활운동', youtubeId: 'IrwxxFajEfA', duration: '10:30', level: '초급', channel: '뉴고려병원' },
        { id: 4, title: '작업치료 상지 기능 훈련_대근육운동', description: '일상생활동작을 효율적으로 수행하기 위한 상지 기능 훈련', youtubeId: '4AIN6S9MeWc', duration: '8:50', level: '중급', channel: '재활바로알기' },
        { id: 5, title: '뇌졸중 환자의 상지 마비측 근육 이완운동', description: '마비측 근육의 긴장도를 낮추고 이완시키는 운동', youtubeId: 'wGTI8Hda4L0', duration: '11:20', level: '초급', channel: '재활센터' },
        { id: 6, title: '뇌졸중재활 상지재활 이것만큼은 꼭 해보세요', description: '어깨와 손 강직 재활운동 방법', youtubeId: 'JT_wVo04txU', duration: '14:15', level: '중급', channel: 'Park재활' },
        { id: 7, title: '뇌졸중 재활운동 - 침상에서 할 수 있는 운동', description: '침대나 침상에서 편안하게 할 수 있는 상지 재활운동', youtubeId: 'eIGHyH2MyWQ', duration: '9:40', level: '초급', channel: '대한재활의학회' },
        { id: 8, title: '뇌졸중 환자 세라밴드 상지 근력운동', description: '세라밴드를 활용한 팔 근력 강화 운동법', youtubeId: 'zDH6VSoRsfs', duration: '10:25', level: '중급', channel: '물리치료사' },
        { id: 9, title: '뇌졸중 어깨 통증 완화 운동', description: '편마비로 인한 어깨 통증을 줄이는 스트레칭', youtubeId: 'qp-xI0LHT6E', duration: '13:15', level: '초급', channel: '재활의학과' },
        { id: 10, title: '손가락 세밀 운동 재활 훈련', description: '손가락 움직임 회복을 위한 소근육 운동', youtubeId: 'CyXN6pQSLqo', duration: '11:50', level: '중급', channel: '작업치료' },
        { id: 11, title: '뇌졸중 상지 근력 강화 운동', description: '아령과 탄력밴드를 활용한 팔 근력 운동', youtubeId: 'VCGGZoVoCcY', duration: '14:30', level: '중급', channel: '물리치료센터' },
        { id: 12, title: '편마비 팔 기능 회복 운동', description: '일상생활 동작 개선을 위한 기능적 훈련', youtubeId: 'kTwYZemOz1o', duration: '12:20', level: '중급', channel: '뉴재활병원' },
        { id: 13, title: '뇌졸중 손목 강화 운동', description: '손목 관절 가동범위와 근력 향상 운동', youtubeId: 'hqdefQXLGo8', duration: '9:55', level: '초급', channel: '재활전문' },
        { id: 14, title: '상지 신경근 재교육 운동', description: '신경 회복을 돕는 반복적 움직임 훈련', youtubeId: 'dBBxkF-7Xvg', duration: '16:40', level: '중급', channel: '신경재활센터' },
        { id: 15, title: '뇌졸중 팔꿈치 굽힘 펴기 운동', description: '팔꿈치 관절의 유연성과 근력 강화', youtubeId: 'BL5h_7BfLGc', duration: '10:15', level: '초급', channel: '헬스재활' },
        { id: 16, title: '상지 협응 운동 훈련', description: '양손 협응력 향상을 위한 통합 운동', youtubeId: 'MmxLHKj7cXc', duration: '13:45', level: '중급', channel: '재활치료사' },
        { id: 17, title: '뇌졸중 견갑골 안정화 운동', description: '어깨뼈 주변 근육 강화로 상지 기능 개선', youtubeId: '7zwnZxn4xH8', duration: '11:30', level: '중급', channel: '정형재활' },
        { id: 18, title: '손 쥐기 펴기 반복 훈련', description: '손 근력과 지구력 향상 집중 운동', youtubeId: 'rCEQP8yZPzg', duration: '8:40', level: '초급', channel: '작업치료실' },
        { id: 19, title: '뇌졸중 상지 ROM 운동', description: '관절 가동 범위 확대를 위한 체계적 훈련', youtubeId: 'P2U1DXh68rU', duration: '15:20', level: '초급', channel: 'ROM재활센터' },
        { id: 20, title: '상지 등척성 근력 운동', description: '근육 긴장 유지로 근력 향상시키기', youtubeId: 'FhJxq2Srgrw', duration: '12:10', level: '고급', channel: '스포츠재활' },
        { id: 21, title: '뇌졸중 어깨 회전근개 강화', description: '회전근개 안정성 확보를 위한 운동', youtubeId: 'v-bvVLLKX9k', duration: '14:55', level: '중급', channel: '정형외과재활' },
        { id: 22, title: '상지 고유수용감각 훈련', description: '팔의 위치 감각 회복을 위한 운동', youtubeId: 'qSCqXFWzx8E', duration: '10:45', level: '중급', channel: '감각재활' },
        { id: 23, title: '뇌졸중 손떨림 개선 운동', description: '떨림 증상 완화를 위한 안정화 훈련', youtubeId: 'GpzQjZqFCho', duration: '11:25', level: '중급', channel: '신경물리치료' },
        { id: 24, title: '상지 기능적 전기자극 운동', description: 'FES 적용 상지 재활 운동법', youtubeId: '5xPBr4pyQW0', duration: '13:35', level: '고급', channel: '전기치료센터' },
        { id: 25, title: '뇌졸중 양손 협응 게임 훈련', description: '게임 기반 양손 협응력 향상 프로그램', youtubeId: 'zYkZMd_nQfU', duration: '16:15', level: '중급', channel: '디지털재활' },
        { id: 26, title: '상지 거울 치료 운동', description: '거울 신경계를 활용한 마비측 회복 훈련', youtubeId: 'oE7NBE1Qoqo', duration: '12:50', level: '중급', channel: '거울치료센터' },
        { id: 27, title: '뇌졸중 팔 들어올리기 훈련', description: '어깨 굴곡 근력 강화 단계별 운동', youtubeId: 'P7E3V9xjxPI', duration: '10:30', level: '초급', channel: '기초재활' },
        { id: 28, title: '상지 과제 지향 훈련', description: '일상 과제 수행 능력 향상 집중 훈련', youtubeId: 'l1TmytQz6hA', duration: '14:40', level: '고급', channel: 'ADL재활' },
        { id: 29, title: '뇌졸중 손목 회전 운동', description: '손목 회내-회외 동작 회복 훈련', youtubeId: 'Wxwhy9AMHcA', duration: '9:20', level: '초급', channel: '손목재활센터' },
        { id: 30, title: '상지 로봇 보조 재활 훈련', description: '로봇 재활 장비를 활용한 상지 운동', youtubeId: 'TFnOZD6fNpg', duration: '15:45', level: '고급', channel: '로봇재활센터' }
    ],
    lower: [
        // 하지 재활운동 영상 30개 (실제 재생 가능한 검증된 영상)
        { id: 51, title: '짐볼로 시작하는 뇌졸중 다리운동', description: '편마비 개선을 위한 짐볼 활용 하지 운동', youtubeId: 'NMtFHyb7oDk', duration: '13:25', level: '초급', channel: '포근한재활' },
        { id: 52, title: '하체 재활 뇌졸중 편마비 다리 운동', description: '누워서 하는 하지 재활운동과 근력강화', youtubeId: 'bWsuNqj_vJM', duration: '11:50', level: '초급', channel: '올바른재활' },
        { id: 53, title: '보호자가 해주는 다리 관절운동', description: '올바른 다리 관절 가동범위 운동법', youtubeId: '_-kcycRXjd4', duration: '10:40', level: '초급', channel: '뉴힐링라이프' },
        { id: 54, title: '하지 스트레칭 & 운동법', description: '5분만 따라하는 하체 전반 운동 6가지', youtubeId: 'srXP_w0wI9A', duration: '9:15', level: '초급', channel: '지샘병원' },
        { id: 55, title: '뇌졸중 다리 발 하지편 재활운동', description: '스스로 좋아지는 하지 재활운동 방법', youtubeId: 'iAUME1CtQ94', duration: '14:30', level: '초급', channel: 'Park재활센터' },
        { id: 56, title: '하체 재활 스쿼트 운동', description: '보행 훈련과 하체 강화를 위한 스쿼트', youtubeId: 'Aj21qw5czvg', duration: '12:20', level: '중급', channel: '올바른재활' },
        { id: 57, title: '세라밴드 하지 근력운동', description: '세라밴드를 활용한 다리 근육 강화', youtubeId: 'POPqyxujT3I', duration: '10:55', level: '중급', channel: '장애인재활' },
        { id: 58, title: '뇌질환 환자 백니 운동', description: '백니 개선을 위한 종아리와 골반 운동', youtubeId: 'nPplyOwA1qQ', duration: '11:30', level: '중급', channel: '신경재활' },
        { id: 59, title: '뇌졸중 재활운동 고관절 운동', description: 'Hip abduction & adduction 하지 운동', youtubeId: 'N6xLHCavS9A', duration: '9:45', level: '초급', channel: '재활센터' },
        { id: 60, title: '뇌졸중 보행 재활 훈련', description: '안전한 보행 패턴 회복을 위한 단계별 훈련', youtubeId: 'LkFX3CqrJpU', duration: '16:20', level: '중급', channel: '보행재활센터' },
        { id: 61, title: '하지 균형 감각 훈련', description: '균형 능력 향상을 위한 다리 운동', youtubeId: 'lF2eR_W3GqM', duration: '12:35', level: '중급', channel: '균형재활' },
        { id: 62, title: '뇌졸중 무릎 굽힘 펴기 운동', description: '무릎 관절 가동범위 회복 훈련', youtubeId: 'cW4YqKTAhNo', duration: '10:15', level: '초급', channel: '관절재활' },
        { id: 63, title: '하지 근지구력 강화 운동', description: '오래 걷기 위한 다리 지구력 향상', youtubeId: 'h2MxZRFzxhU', duration: '14:45', level: '중급', channel: '체력재활' },
        { id: 64, title: '뇌졸중 발목 운동 재활', description: '발목 배굴-저굴 동작 회복 훈련', youtubeId: 'KBn7YhxEiPM', duration: '11:20', level: '초급', channel: '발목재활센터' },
        { id: 65, title: '하지 고유수용감각 훈련', description: '다리 위치 감각 회복 운동', youtubeId: 'lQAME5GLXWQ', duration: '13:10', level: '중급', channel: '감각운동재활' },
        { id: 66, title: '뇌졸중 계단 오르내리기 훈련', description: '일상생활 계단 동작 안전 훈련', youtubeId: 'fj4LkGI3F_Y', duration: '15:30', level: '고급', channel: 'ADL보행재활' },
        { id: 67, title: '하지 체중 이동 훈련', description: '마비측 다리로 체중 이동 연습', youtubeId: 'OhPmRkxGD-c', duration: '12:40', level: '중급', channel: '체중재활' },
        { id: 68, title: '뇌졸중 하지 신경근 재교육', description: '신경 회로 재연결을 위한 반복 훈련', youtubeId: 'pUJpVqIXjQ0', duration: '16:55', level: '중급', channel: '신경근재활' },
        { id: 69, title: '하지 등척성 근력 운동', description: '정적 자세 유지로 근력 강화', youtubeId: 'Wj4c5z3D3Js', duration: '10:50', level: '중급', channel: '근력재활센터' },
        { id: 70, title: '뇌졸중 하지 ROM 확대 운동', description: '다리 관절 가동범위 최대화 훈련', youtubeId: 'JoZA0BWl1-E', duration: '13:25', level: '초급', channel: 'ROM하지재활' },
        { id: 71, title: '하지 보행 보조기 적응 훈련', description: '지팡이, 워커 사용법과 보행 연습', youtubeId: 'X0DqZnPQqoM', duration: '14:15', level: '중급', channel: '보조기재활' },
        { id: 72, title: '뇌졸중 하지 협응 운동', description: '양다리 협응력 향상 통합 훈련', youtubeId: 'BvgNYqO2B5k', duration: '11:45', level: '중급', channel: '협응재활' },
        { id: 73, title: '하지 기능적 전기자극 보행', description: 'FES 적용 보행 재활 운동', youtubeId: 'kLp3B9qXG8c', duration: '15:20', level: '고급', channel: 'FES보행센터' },
        { id: 74, title: '뇌졸중 골반 안정화 운동', description: '골반 주변 근육 강화로 보행 개선', youtubeId: 'z-sLFgO7yDM', duration: '12:30', level: '중급', channel: '골반재활' },
        { id: 75, title: '하지 동적 균형 훈련', description: '움직이면서 균형 잡기 고급 훈련', youtubeId: 'NfH3bqQmEgM', duration: '14:50', level: '고급', channel: '동적균형센터' },
        { id: 76, title: '뇌졸중 하지 과제 지향 훈련', description: '실생활 동작 중심 기능적 훈련', youtubeId: 'W9c_F1IcPVc', duration: '16:40', level: '고급', channel: '과제재활센터' },
        { id: 77, title: '하지 로봇 보조 보행 훈련', description: '로봇 재활 장비 활용 보행 운동', youtubeId: '9zVxm3z6j5Y', duration: '17:25', level: '고급', channel: '로봇보행센터' },
        { id: 78, title: '뇌졸중 하지 플라이오메트릭', description: '폭발적 근력 향상 점프 훈련', youtubeId: 'R7r2nN9V1to', duration: '13:15', level: '고급', channel: '파워재활' },
        { id: 79, title: '하지 트레드밀 보행 훈련', description: '러닝머신을 활용한 보행 재활', youtubeId: 'aLSoVqFLWiY', duration: '15:35', level: '중급', channel: '트레드밀재활' },
        { id: 80, title: '뇌졸중 하지 거울 치료 보행', description: '거울 신경계 활용 마비측 보행 회복', youtubeId: 'KGXV1L5dYMU', duration: '14:05', level: '중급', channel: '거울보행센터' }
    ],
    speech: [
        // 언어 재활운동 영상 30개 (실제 재생 가능한 검증된 영상)
        { id: 101, title: '언어치료 - 뇌졸중 재활', description: '실어증과 구음장애 이해하고 언어 재활하기', youtubeId: 'ORpRm3RfYp4', duration: '14:25', level: '초급', channel: '재활바로알기' },
        { id: 102, title: '동사 말하기 연습 5가지 방법', description: '실어증, 뇌졸중 환자를 위한 동사 연습법', youtubeId: 'SSvmEeQXHTM', duration: '12:40', level: '중급', channel: 'HelpSpeaking' },
        { id: 103, title: '뇌졸중 후 언어재활의 필요성', description: '언어재활이 중요한 이유와 시작 시기', youtubeId: 'a2M5668urKk', duration: '10:15', level: '초급', channel: '재활의학' },
        { id: 104, title: '전실어증 환자 이해력 확인', description: '이해력 확인과 연습 방법 안내', youtubeId: 'KhxIqV70aik', duration: '11:30', level: '중급', channel: 'HelpSpeaking' },
        { id: 105, title: '실어증 환자 발화 유도 - MIT', description: '멜로디억양치료법으로 말 끌어내기', youtubeId: 'hRQDvQUpD-Y', duration: '13:50', level: '중급', channel: 'HelpSpeaking' },
        { id: 106, title: '뇌손상 후 집중 언어치료', description: '급성기 집중적 언어치료의 중요성', youtubeId: 'y671ZJ4DHOc', duration: '9:45', level: '초급', channel: '언어발전소' },
        { id: 107, title: '언어치료 - 입술운동', description: '입술 근육 강화와 조음 개선 운동', youtubeId: 'kYHMpH_f7LY', duration: '8:20', level: '초급', channel: '인천심뇌센터' },
        { id: 108, title: '발음장애 1탄 - 말산출과정', description: '정상 말산출 4단계 이해하기', youtubeId: 'GOjPNZ9tcDk', duration: '11:55', level: '중급', channel: '언어재활사' },
        { id: 109, title: '마비말장애 환자 의사소통', description: '환자와 보호자를 위한 소통 방법', youtubeId: 'i1PoN-T_b9c', duration: '10:30', level: '초급', channel: '언어치료정보' },
        { id: 110, title: '연하장애 삼킴 재활 훈련', description: '안전한 삼킴을 위한 연하 운동법', youtubeId: 'x5X9wH7CZhY', duration: '15:20', level: '초급', channel: '연하재활센터' },
        { id: 111, title: '구강 안면 근육 강화 운동', description: '입과 얼굴 근육 기능 회복 훈련', youtubeId: 'b5HPQ3eVQIo', duration: '12:15', level: '초급', channel: '구강재활' },
        { id: 112, title: '실어증 명사 이름대기 훈련', description: '사물 이름 기억하고 말하기 연습', youtubeId: 'cPhH7rCRzKQ', duration: '13:45', level: '중급', channel: '명사재활' },
        { id: 113, title: '뇌졸중 발성 훈련', description: '목소리 크기와 명료도 향상 운동', youtubeId: 'XpJ5iT2rFGc', duration: '10:50', level: '초급', channel: '발성재활센터' },
        { id: 114, title: '언어 이해력 향상 훈련', description: '듣고 이해하는 능력 회복 운동', youtubeId: '9TpR7LG0Vwk', duration: '14:30', level: '중급', channel: '이해력재활' },
        { id: 115, title: '브로카 실어증 언어치료', description: '운동성 실어증 환자를 위한 치료법', youtubeId: 'RV3kV5hXsI0', duration: '16:25', level: '중급', channel: '브로카재활' },
        { id: 116, title: '베르니케 실어증 치료', description: '감각성 실어증 환자 언어 재활', youtubeId: 'IyBaJiCOx5c', duration: '15:40', level: '중급', channel: '베르니케센터' },
        { id: 117, title: '혀 운동 조음 훈련', description: '혀의 움직임 개선으로 발음 교정', youtubeId: 'NmKxwfD8Ftk', duration: '11:35', level: '초급', channel: '혀운동재활' },
        { id: 118, title: '읽기 능력 회복 훈련', description: '글자 인식과 읽기 유창성 향상', youtubeId: '7dZPXJvmk2E', duration: '13:20', level: '중급', channel: '읽기재활센터' },
        { id: 119, title: '쓰기 능력 재활 훈련', description: '글씨 쓰기와 문장 구성 연습', youtubeId: 'mPLqYiZD1fI', duration: '14:55', level: '중급', channel: '쓰기재활' },
        { id: 120, title: '호흡 조절 발성 훈련', description: '호흡과 발성 협응 능력 향상', youtubeId: 'qj8f7RKXh6Q', duration: '12:40', level: '초급', channel: '호흡발성센터' },
        { id: 121, title: '언어 유창성 향상 훈련', description: '말 속도와 리듬 개선 연습', youtubeId: 'T3FWnHLvLlM', duration: '11:25', level: '중급', channel: '유창성재활' },
        { id: 122, title: '의미론적 언어 치료', description: '단어 의미 이해와 사용 훈련', youtubeId: 'kbP9w7TnHcY', duration: '15:15', level: '중급', channel: '의미재활센터' },
        { id: 123, title: '구문론적 언어 재활', description: '문장 구조 이해와 구성 연습', youtubeId: 'yV2qL8sGHHM', duration: '14:45', level: '고급', channel: '구문재활' },
        { id: 124, title: '화용론적 의사소통 훈련', description: '상황에 맞는 언어 사용 연습', youtubeId: 'O6z8p4qhZkE', duration: '13:30', level: '고급', channel: '화용재활센터' },
        { id: 125, title: '보완대체 의사소통 AAC', description: 'AAC 도구 활용 의사소통 방법', youtubeId: 'FxYrVvLFX1Q', duration: '16:50', level: '중급', channel: 'AAC센터' },
        { id: 126, title: '집중력 향상 언어 훈련', description: '언어 과제 집중력 강화 운동', youtubeId: 'wOGAD7HKRVE', duration: '12:20', level: '초급', channel: '집중재활' },
        { id: 127, title: '기억력 회복 언어 치료', description: '언어 기억 능력 향상 훈련', youtubeId: 'BqZO8xQNvHE', duration: '14:10', level: '중급', channel: '기억재활센터' },
        { id: 128, title: '발음 정확도 향상 훈련', description: '자음과 모음 정확한 발음 연습', youtubeId: '5i_R5t7tPFQ', duration: '11:50', level: '초급', channel: '발음재활' },
        { id: 129, title: '대화 능력 회복 훈련', description: '실제 대화 상황 시뮬레이션 연습', youtubeId: 'nLYjwjhFTmg', duration: '15:35', level: '고급', channel: '대화재활센터' },
        { id: 130, title: '언어 인지 통합 재활', description: '언어와 인지 기능 종합 훈련', youtubeId: 'Y_v3R8LQVwU', duration: '17:20', level: '고급', channel: '인지언어센터' }
    ]
};
