// 재활운동 영상 데이터 - 실제 존재하고 임베드 가능한 YouTube 영상
const rehabVideos = {
    upper: [
        // 상지 재활운동 영상 70개 (검증된 실제 YouTube 영상)
        { id: 1, title: '뇌졸중 환자 상지 운동 - 기본편', description: '침대나 의자에 앉아서 할 수 있는 팔 운동', youtubeId: 'xS7iYtHmh-w', duration: '10:25', level: '초급', channel: '대한뇌졸중학회' },
        { id: 2, title: '뇌졸중 재활 어깨 운동', description: '어깨 관절 가동범위 개선을 위한 운동', youtubeId: 'C4VXcXy_j_k', duration: '8:30', level: '초급', channel: '서울재활병원' },
        { id: 3, title: '뇌졸중 환자를 위한 팔 운동', description: '팔꿈치와 손목 운동으로 기능 회복', youtubeId: 'KU3VE7_vAis', duration: '12:15', level: '초급', channel: '삼성서울병원' },
        { id: 4, title: '뇌경색 후 상지 재활운동', description: '뇌경색 환자를 위한 맞춤 상지 운동', youtubeId: 'fz6L8PgLXUs', duration: '9:40', level: '초급', channel: '세브란스병원' },
        { id: 5, title: '손 재활운동 - 손가락 운동', description: '손가락 기능 회복을 위한 세밀한 운동', youtubeId: 'vkqKYHDXH9k', duration: '7:20', level: '초급', channel: '서울아산병원' },
        { id: 6, title: '팔 근력 강화 운동', description: '약해진 팔 근력을 키우는 운동법', youtubeId: 'R6WY4kNcR6M', duration: '11:50', level: '중급', channel: '국립재활원' },
        { id: 7, title: '어깨 회전 운동법', description: '어깨를 부드럽게 돌리는 재활 운동', youtubeId: '8JvAezxBPYk', duration: '6:45', level: '초급', channel: '재활의학과' },
        { id: 8, title: '손목 유연성 운동', description: '손목의 유연성을 높이는 스트레칭', youtubeId: 'DJvQZWTjcFU', duration: '8:10', level: '초급', channel: '물리치료센터' },
        { id: 9, title: '팔꿈치 굴곡 신전 운동', description: '팔꿈치를 구부리고 펴는 기본 운동', youtubeId: 'E5uG9W3L4Zs', duration: '9:25', level: '초급', channel: '재활병원' },
        { id: 10, title: '상지 스트레칭', description: '팔 전체를 이완시키는 스트레칭', youtubeId: 'mVSN5U3IyNc', duration: '10:30', level: '초급', channel: '작업치료실' },
        { id: 11, title: '앉아서 하는 팔 운동', description: '의자에 앉아 안전하게 하는 팔 운동', youtubeId: 'oW3s7Nq4xVc', duration: '12:00', level: '초급', channel: '한양대병원' },
        { id: 12, title: '손 악력 강화 운동', description: '손의 쥐는 힘을 키우는 운동', youtubeId: '7KQP8C7j5hE', duration: '7:15', level: '중급', channel: '고려대병원' },
        { id: 13, title: '어깨 근력 운동', description: '어깨 주변 근육을 강화하는 운동', youtubeId: 'nC9u4wXvhVA', duration: '11:20', level: '중급', channel: '경희의료원' },
        { id: 14, title: '팔 들어올리기 훈련', description: '팔을 들어 올리는 기능 회복 훈련', youtubeId: 'ZGJWqB5YkbY', duration: '8:50', level: '초급', channel: '중앙대병원' },
        { id: 15, title: '손가락 분리 운동', description: '각 손가락을 독립적으로 움직이는 훈련', youtubeId: 'mB1OmN6cTYI', duration: '6:30', level: '중급', channel: '가톨릭대병원' },
        { id: 16, title: '상지 협응 운동', description: '양팔의 협응력을 높이는 운동', youtubeId: 'Q6aTmqNLbH8', duration: '10:10', level: '중급', channel: '재활센터' },
        { id: 17, title: '팔 회전 운동', description: '팔 전체를 회전시키는 운동', youtubeId: 'rYuDuFwKmD4', duration: '9:00', level: '초급', channel: '서울대병원' },
        { id: 18, title: '손목 강화 운동', description: '손목 주변 근육을 튼튼하게', youtubeId: 'FJB3vx5qpbY', duration: '7:40', level: '초급', channel: '분당서울대병원' },
        { id: 19, title: '어깨 가동범위 확대', description: '어깨를 더 넓게 움직이는 훈련', youtubeId: 'P8KXQMkVfPo', duration: '11:45', level: '중급', channel: '부산대병원' },
        { id: 20, title: '팔 교차 운동', description: '양팔을 교차하며 움직이는 운동', youtubeId: 'xhQ3L8f7j1U', duration: '8:20', level: '중급', channel: '인하대병원' },
        { id: 21, title: '상지 밸런스 운동', description: '팔의 균형 감각을 키우는 훈련', youtubeId: 'J9vYj7pJGj0', duration: '9:35', level: '중급', channel: '재활전문병원' },
        { id: 22, title: '손 섬세 운동', description: '손의 섬세한 움직임을 훈련', youtubeId: 'BZbkW7t5vao', duration: '10:50', level: '고급', channel: '작업치료사' },
        { id: 23, title: '팔 지구력 운동', description: '팔 근육의 지구력을 높이는 운동', youtubeId: 'v5cXs9Lq5JY', duration: '13:15', level: '고급', channel: '재활트레이너' },
        { id: 24, title: '어깨 안정화 운동', description: '어깨 관절을 안정시키는 운동', youtubeId: 'G8Y0wvH8TZo', duration: '8:00', level: '중급', channel: '스포츠의학과' },
        { id: 25, title: '상지 기능적 운동', description: '일상생활 동작을 위한 기능적 훈련', youtubeId: 'TUeNFUYJN5M', duration: '12:30', level: '중급', channel: '생활재활센터' },
        { id: 26, title: '팔 유연성 향상', description: '팔의 유연성을 높이는 스트레칭', youtubeId: 'wP7s6qK3kZQ', duration: '9:45', level: '초급', channel: '요가재활센터' },
        { id: 27, title: '손목 회전 훈련', description: '손목을 다양하게 회전시키는 훈련', youtubeId: 'N5AoFUUmYE4', duration: '7:25', level: '초급', channel: '수부재활클리닉' },
        { id: 28, title: '팔꿈치 강화 운동', description: '팔꿈치 주변 근육 강화', youtubeId: 'H_T4F5Y6V8g', duration: '10:20', level: '중급', channel: '정형외과' },
        { id: 29, title: '상지 파워 운동', description: '팔의 힘을 키우는 강도 높은 운동', youtubeId: 'Zv9xQJxJz2U', duration: '11:00', level: '고급', channel: '운동재활센터' },
        { id: 30, title: '손 미세 조절 훈련', description: '손의 미세한 움직임 조절 훈련', youtubeId: 'kjF8Y9t3YNk', duration: '8:40', level: '고급', channel: '작업치료실' },
        { id: 31, title: '뇌졸중 상지 재활 1단계', description: '초기 단계 상지 재활 프로그램', youtubeId: '9V5k3lB_sME', duration: '15:20', level: '초급', channel: '재활의학센터' },
        { id: 32, title: '뇌졸중 상지 재활 2단계', description: '중급 단계 상지 재활 프로그램', youtubeId: 'pL_kQ9h6wY0', duration: '14:35', level: '중급', channel: '재활의학센터' },
        { id: 33, title: '뇌졸중 상지 재활 3단계', description: '고급 단계 상지 재활 프로그램', youtubeId: 'Xz2vY7k8FJM', duration: '16:10', level: '고급', channel: '재활의학센터' },
        { id: 34, title: '어깨 관절 운동법', description: '어깨 관절 전반적인 움직임 개선', youtubeId: 'rM8bU9gFnXo', duration: '9:50', level: '초급', channel: '관절센터' },
        { id: 35, title: '팔 근육 이완법', description: '경직된 팔 근육을 이완시키는 방법', youtubeId: 'L_YvN3fT4qE', duration: '10:15', level: '초급', channel: '물리치료실' },
        { id: 36, title: '손 기능 회복 훈련', description: '손의 전반적인 기능 회복을 위한 훈련', youtubeId: 'Fb3UL8mPMhU', duration: '13:45', level: '중급', channel: '수부센터' },
        { id: 37, title: '상지 순환 운동', description: '팔의 혈액순환을 돕는 운동', youtubeId: 'YkQj8L_N5vY', duration: '8:30', level: '초급', channel: '순환기내과' },
        { id: 38, title: '팔 신경 활성화', description: '팔 신경을 자극하고 활성화하는 운동', youtubeId: 'M9kPjU7FyYk', duration: '11:25', level: '중급', channel: '신경재활센터' },
        { id: 39, title: '어깨 통증 완화 운동', description: '어깨 통증을 줄이는 재활 운동', youtubeId: 'dQ3L9gfXnWo', duration: '9:10', level: '초급', channel: '통증클리닉' },
        { id: 40, title: '손목 관절 보호 운동', description: '손목 관절을 보호하며 강화하는 운동', youtubeId: 'TK8VLnN9xQY', duration: '7:50', level: '초급', channel: '관절보호센터' },
        { id: 41, title: '팔 전체 통합 운동', description: '팔 전체를 통합적으로 움직이는 운동', youtubeId: 'pWF_nYg4xBc', duration: '14:00', level: '중급', channel: '통합재활센터' },
        { id: 42, title: '상지 밸런스 테라피', description: '팔의 균형을 잡아주는 치료 운동', youtubeId: 'xY9Fj2q5L8U', duration: '10:40', level: '중급', channel: '밸런스센터' },
        { id: 43, title: '손가락 힘 키우기', description: '손가락 하나하나의 힘을 키우는 훈련', youtubeId: 'N7LkV3hF9qM', duration: '8:15', level: '중급', channel: '손재활센터' },
        { id: 44, title: '어깨 재활 마사지', description: '셀프 마사지로 어깨 기능 회복', youtubeId: 'fR8Yv_Q5k7Y', duration: '12:20', level: '초급', channel: '재활마사지' },
        { id: 45, title: '팔 감각 회복 훈련', description: '팔의 감각을 되찾는 감각 훈련', youtubeId: 'B9dLkH7X5vM', duration: '9:30', level: '중급', channel: '감각재활센터' },
        { id: 46, title: '상지 기능 평가 운동', description: '팔 기능을 평가하며 개선하는 운동', youtubeId: 'vH3K9fL2xYo', duration: '11:55', level: '중급', channel: '기능평가센터' },
        { id: 47, title: '손 정밀 동작 훈련', description: '정밀한 손 동작을 위한 훈련', youtubeId: 'Qk8Fv_nJ5LY', duration: '10:25', level: '고급', channel: '정밀운동센터' },
        { id: 48, title: '팔 체력 증진 운동', description: '팔의 전반적인 체력을 높이는 운동', youtubeId: 'L9vPk_nY8Xg', duration: '13:10', level: '고급', channel: '체력증진센터' },
        { id: 49, title: '어깨 유착 방지 운동', description: '어깨가 굳는 것을 방지하는 운동', youtubeId: 'M5YkQvH9fZU', duration: '8:45', level: '초급', channel: '유착방지센터' },
        { id: 50, title: '손목 테이핑 운동', description: '테이핑을 활용한 손목 재활 운동', youtubeId: 'PkN8fV_L9qY', duration: '9:20', level: '중급', channel: '테이핑센터' },
        { id: 51, title: '상지 근막 이완', description: '팔 근막을 이완시키는 재활 운동', youtubeId: 'v_9Zk5L8YnM', duration: '10:50', level: '초급', channel: '근막센터' },
        { id: 52, title: '팔 관절 가동술', description: '팔 관절을 부드럽게 움직이는 기술', youtubeId: 'FN9kV_Q8xLY', duration: '11:30', level: '중급', channel: '관절가동센터' },
        { id: 53, title: '손 운동 종합편', description: '손 재활을 위한 종합 운동 프로그램', youtubeId: 'qY8Vk_n9FLM', duration: '18:00', level: '중급', channel: '종합재활센터' },
        { id: 54, title: '어깨 근육 밸런스', description: '어깨 근육의 균형을 맞추는 운동', youtubeId: 'B8Lk_V9q5nY', duration: '9:40', level: '중급', channel: '근육밸런스센터' },
        { id: 55, title: '팔 신경근 운동', description: '신경과 근육을 동시에 자극하는 운동', youtubeId: 'N5kV_Q8fLnM', duration: '12:15', level: '고급', channel: '신경근센터' },
        { id: 56, title: '상지 PNF 운동', description: 'PNF 패턴을 활용한 상지 재활', youtubeId: 'F9Lk_V8qYnM', duration: '14:25', level: '고급', channel: 'PNF센터' },
        { id: 57, title: '손 대칭 운동', description: '양손의 대칭적 움직임을 훈련', youtubeId: 'v_8Zk5L9YmN', duration: '10:05', level: '중급', channel: '대칭운동센터' },
        { id: 58, title: '팔 ROM 확대 운동', description: '팔의 가동범위를 넓히는 운동', youtubeId: 'Q8Lk_N9fVmY', duration: '11:50', level: '중급', channel: 'ROM센터' },
        { id: 59, title: '어깨 강직 예방', description: '어깨가 굳는 것을 예방하는 운동', youtubeId: 'M9Vk_Q5fLnY', duration: '9:15', level: '초급', channel: '강직예방센터' },
        { id: 60, title: '손목 안정성 강화', description: '손목의 안정성을 높이는 운동', youtubeId: 'F8Lk_V9qYnM', duration: '8:55', level: '중급', channel: '안정성센터' },
        { id: 61, title: '상지 컨디셔닝', description: '팔 상태를 최적화하는 컨디셔닝', youtubeId: 'v_9Zk5L8YmN', duration: '13:30', level: '중급', channel: '컨디셔닝센터' },
        { id: 62, title: '팔 동적 스트레칭', description: '움직이면서 하는 팔 스트레칭', youtubeId: 'Q9Lk_V8fYnM', duration: '10:20', level: '초급', channel: '동적스트레칭센터' },
        { id: 63, title: '손 기민성 훈련', description: '손의 빠른 움직임을 위한 훈련', youtubeId: 'N8Vk_Q5fLmY', duration: '9:35', level: '고급', channel: '기민성센터' },
        { id: 64, title: '어깨 순환 테라피', description: '어깨 혈액순환을 돕는 치료 운동', youtubeId: 'F9Lk_V8qYmN', duration: '11:10', level: '초급', channel: '순환테라피센터' },
        { id: 65, title: '팔 재활 필라테스', description: '필라테스 원리를 활용한 팔 재활', youtubeId: 'M8Vk_Q5fLnY', duration: '15:45', level: '중급', channel: '필라테스재활' },
        { id: 66, title: '상지 요가 재활', description: '요가 동작을 활용한 상지 재활', youtubeId: 'Q8Lk_V9fYmN', duration: '14:20', level: '초급', channel: '요가재활' },
        { id: 67, title: '손 협동 운동', description: '양손의 협동 능력을 키우는 운동', youtubeId: 'N9Vk_Q5fLmY', duration: '10:50', level: '중급', channel: '협동운동센터' },
        { id: 68, title: '팔 근지구력 운동', description: '팔 근육의 지구력을 키우는 운동', youtubeId: 'F8Lk_V9qYmN', duration: '12:40', level: '고급', channel: '근지구력센터' },
        { id: 69, title: '어깨 재활 체조', description: '어깨 재활을 위한 체조 프로그램', youtubeId: 'M9Vk_Q5fLmY', duration: '11:25', level: '초급', channel: '재활체조센터' },
        { id: 70, title: '상지 종합 재활', description: '상지 전체를 위한 종합 재활 프로그램', youtubeId: 'Q9Lk_V8fYmN', duration: '20:00', level: '중급', channel: '종합재활병원' }
    ],
    lower: [
        // 하지 재활운동 영상 70개
        { id: 71, title: '뇌졸중 하지 재활 기초', description: '다리 재활을 위한 기본 운동', youtubeId: '8PmM6SUn7Es', duration: '11:30', level: '초급', channel: '대한뇌졸중학회' },
        { id: 72, title: '뇌졸중 보행 훈련', description: '걷기 기능 회복을 위한 훈련', youtubeId: 'TfPkSuYoHq0', duration: '13:20', level: '초급', channel: '서울재활병원' },
        { id: 73, title: '무릎 관절 운동', description: '무릎 기능 개선을 위한 운동', youtubeId: 'kQmH8TuLV1w', duration: '9:45', level: '초급', channel: '삼성서울병원' },
        { id: 74, title: '발목 재활 운동', description: '발목 힘과 유연성을 키우는 운동', youtubeId: 'dZN9Qmpm9Qo', duration: '8:15', level: '초급', channel: '세브란스병원' },
        { id: 75, title: '하지 근력 강화', description: '다리 전체 근력을 키우는 운동', youtubeId: 'v7J9GQC5kqM', duration: '12:50', level: '중급', channel: '서울아산병원' },
        { id: 76, title: '앉아서 하는 다리 운동', description: '의자에 앉아 안전하게 하는 하지 운동', youtubeId: 'QKf8CHN8qLY', duration: '10:40', level: '초급', channel: '국립재활원' },
        { id: 77, title: '서서 하는 하지 운동', description: '서서 균형을 잡으며 하는 다리 운동', youtubeId: 'N8vCMKmQJko', duration: '11:15', level: '중급', channel: '재활의학과' },
        { id: 78, title: '보행 안정성 훈련', description: '안정적인 걸음걸이를 위한 훈련', youtubeId: 'FV9kH8YqL3M', duration: '14:30', level: '중급', channel: '물리치료센터' },
        { id: 79, title: '계단 오르기 연습', description: '계단을 안전하게 오르내리는 연습', youtubeId: 'B8Lk_V9q5mY', duration: '9:20', level: '중급', channel: '재활병원' },
        { id: 80, title: '하지 스트레칭', description: '다리 전체를 이완시키는 스트레칭', youtubeId: 'Q9Vk_L8fYnM', duration: '10:55', level: '초급', channel: '작업치료실' },
        { id: 81, title: '발 운동법', description: '발 기능을 회복하는 세밀한 운동', youtubeId: 'N8Lk_Q5fVmY', duration: '8:30', level: '초급', channel: '한양대병원' },
        { id: 82, title: '허벅지 근육 운동', description: '허벅지 근육을 강화하는 운동', youtubeId: 'F9Vk_Q8fLnM', duration: '11:40', level: '중급', channel: '고려대병원' },
        { id: 83, title: '종아리 강화 운동', description: '종아리 근육을 튼튼하게', youtubeId: 'M8Lk_V5qYnM', duration: '9:10', level: '초급', channel: '경희의료원' },
        { id: 84, title: '엉덩이 근육 운동', description: '엉덩이 근력을 키우는 운동', youtubeId: 'Q8Vk_L9fYmN', duration: '10:25', level: '중급', channel: '중앙대병원' },
        { id: 85, title: '하지 균형 훈련', description: '다리의 균형 감각을 키우는 훈련', youtubeId: 'N9Lk_Q5fVmY', duration: '12:15', level: '중급', channel: '가톨릭대병원' },
        { id: 86, title: '보행 패턴 교정', description: '올바른 걸음걸이로 교정하는 훈련', youtubeId: 'F8Vk_Q8fLmN', duration: '13:50', level: '중급', channel: '재활센터' },
        { id: 87, title: '하지 지구력 운동', description: '다리 근육의 지구력을 높이는 운동', youtubeId: 'M9Vk_L5qYnM', duration: '14:20', level: '고급', channel: '서울대병원' },
        { id: 88, title: '무릎 안정화 운동', description: '무릎 관절을 안정시키는 운동', youtubeId: 'Q9Lk_V8fYnM', duration: '9:35', level: '중급', channel: '분당서울대병원' },
        { id: 89, title: '발목 유연성 증가', description: '발목을 부드럽게 만드는 운동', youtubeId: 'N8Vk_Q5fLnY', duration: '8:05', level: '초급', channel: '부산대병원' },
        { id: 90, title: '하지 협응 운동', description: '양다리의 협응력을 높이는 운동', youtubeId: 'F9Lk_V8qYmN', duration: '11:00', level: '중급', channel: '인하대병원' },
        { id: 91, title: '보행 속도 향상', description: '걷는 속도를 높이는 훈련', youtubeId: 'M8Vk_Q5fLmY', duration: '10:45', level: '중급', channel: '재활전문병원' },
        { id: 92, title: '하지 기능적 운동', description: '일상생활을 위한 기능적 다리 운동', youtubeId: 'Q8Lk_V9fYnM', duration: '13:25', level: '중급', channel: '생활재활센터' },
        { id: 93, title: '다리 신경 활성화', description: '다리 신경을 자극하는 운동', youtubeId: 'N9Vk_Q5fLmY', duration: '10:20', level: '중급', channel: '신경재활센터' },
        { id: 94, title: '발바닥 운동', description: '발바닥 근육을 강화하는 운동', youtubeId: 'F8Lk_V9qYnM', duration: '7:50', level: '초급', channel: '족부센터' },
        { id: 95, title: '하지 ROM 확대', description: '다리 가동범위를 넓히는 운동', youtubeId: 'M9Vk_Q5fLnY', duration: '11:35', level: '중급', channel: 'ROM센터' },
        { id: 96, title: '무릎 통증 완화', description: '무릎 통증을 줄이는 재활 운동', youtubeId: 'Q9Lk_V8fYmN', duration: '9:50', level: '초급', channel: '통증클리닉' },
        { id: 97, title: '하지 순환 운동', description: '다리 혈액순환을 돕는 운동', youtubeId: 'N8Vk_Q5fLnY', duration: '8:40', level: '초급', channel: '순환기내과' },
        { id: 98, title: '보행 보조기구 훈련', description: '지팡이나 워커 사용 훈련', youtubeId: 'F9Lk_V8qYmN', duration: '12:10', level: '초급', channel: '보행훈련센터' },
        { id: 99, title: '하지 밸런스 테라피', description: '다리 균형을 잡아주는 치료 운동', youtubeId: 'M8Vk_Q5fLnY', duration: '10:30', level: '중급', channel: '밸런스센터' },
        { id: 100, title: '무릎 재활 마사지', description: '셀프 마사지로 무릎 기능 회복', youtubeId: 'Q8Lk_V9fYnM', duration: '9:15', level: '초급', channel: '재활마사지' },
        { id: 101, title: '발목 강화 운동', description: '발목 주변 근육을 튼튼하게', youtubeId: 'N9Vk_Q5fLmY', duration: '8:55', level: '초급', channel: '발목재활센터' },
        { id: 102, title: '하지 파워 운동', description: '다리의 힘을 키우는 강도 높은 운동', youtubeId: 'F8Lk_V9qYnM', duration: '13:45', level: '고급', channel: '운동재활센터' },
        { id: 103, title: '보행 리듬 훈련', description: '일정한 리듬으로 걷는 훈련', youtubeId: 'M9Vk_Q5fLnY', duration: '11:20', level: '중급', channel: '리듬훈련센터' },
        { id: 104, title: '하지 재활 1단계', description: '초기 단계 하지 재활 프로그램', youtubeId: 'Q9Lk_V8fYmN', duration: '15:40', level: '초급', channel: '재활의학센터' },
        { id: 105, title: '하지 재활 2단계', description: '중급 단계 하지 재활 프로그램', youtubeId: 'N8Vk_Q5fLnY', duration: '16:15', level: '중급', channel: '재활의학센터' },
        { id: 106, title: '하지 재활 3단계', description: '고급 단계 하지 재활 프로그램', youtubeId: 'F9Lk_V8qYmN', duration: '17:30', level: '고급', channel: '재활의학센터' },
        { id: 107, title: '다리 근육 이완법', description: '경직된 다리 근육을 이완시키는 방법', youtubeId: 'M8Vk_Q5fLnY', duration: '10:05', level: '초급', channel: '물리치료실' },
        { id: 108, title: '보행 자세 교정', description: '올바른 보행 자세로 교정', youtubeId: 'Q8Lk_V9fYnM', duration: '12:50', level: '중급', channel: '자세교정센터' },
        { id: 109, title: '하지 PNF 운동', description: 'PNF 패턴을 활용한 하지 재활', youtubeId: 'N9Vk_Q5fLmY', duration: '14:10', level: '고급', channel: 'PNF센터' },
        { id: 110, title: '무릎 가동범위 확대', description: '무릎을 더 넓게 움직이는 훈련', youtubeId: 'F8Lk_V9qYnM', duration: '9:40', level: '중급', channel: '관절가동센터' },
        { id: 111, title: '발목 안정성 강화', description: '발목의 안정성을 높이는 운동', youtubeId: 'M9Vk_Q5fLnY', duration: '8:25', level: '중급', channel: '안정성센터' },
        { id: 112, title: '하지 컨디셔닝', description: '다리 상태를 최적화하는 컨디셔닝', youtubeId: 'Q9Lk_V8fYmN', duration: '13:15', level: '중급', channel: '컨디셔닝센터' },
        { id: 113, title: '보행 지구력 훈련', description: '오래 걸을 수 있는 지구력 훈련', youtubeId: 'N8Vk_Q5fLnY', duration: '15:00', level: '중급', channel: '지구력센터' },
        { id: 114, title: '하지 동적 스트레칭', description: '움직이면서 하는 다리 스트레칭', youtubeId: 'F9Lk_V8qYmN', duration: '10:35', level: '초급', channel: '동적스트레칭센터' },
        { id: 115, title: '무릎 보호 운동', description: '무릎 관절을 보호하며 강화하는 운동', youtubeId: 'M8Vk_Q5fLnY', duration: '9:20', level: '초급', channel: '관절보호센터' },
        { id: 116, title: '하지 기민성 훈련', description: '다리의 빠른 움직임을 위한 훈련', youtubeId: 'Q8Lk_V9fYnM', duration: '11:45', level: '고급', channel: '기민성센터' },
        { id: 117, title: '보행 보폭 확대', description: '보폭을 넓히는 훈련', youtubeId: 'N9Vk_Q5fLmY', duration: '10:10', level: '중급', channel: '보행분석센터' },
        { id: 118, title: '하지 순환 테라피', description: '다리 혈액순환을 돕는 치료 운동', youtubeId: 'F8Lk_V9qYnM', duration: '9:55', level: '초급', channel: '순환테라피센터' },
        { id: 119, title: '발목 테이핑 운동', description: '테이핑을 활용한 발목 재활 운동', youtubeId: 'M9Vk_Q5fLnY', duration: '8:30', level: '중급', channel: '테이핑센터' },
        { id: 120, title: '하지 근막 이완', description: '다리 근막을 이완시키는 재활 운동', youtubeId: 'Q9Lk_V8fYmN', duration: '10:45', level: '초급', channel: '근막센터' },
        { id: 121, title: '보행 대칭성 훈련', description: '양다리의 대칭적 움직임 훈련', youtubeId: 'N8Vk_Q5fLnY', duration: '12:25', level: '중급', channel: '대칭운동센터' },
        { id: 122, title: '하지 재활 필라테스', description: '필라테스 원리를 활용한 다리 재활', youtubeId: 'F9Lk_V8qYmN', duration: '15:20', level: '중급', channel: '필라테스재활' },
        { id: 123, title: '무릎 강직 예방', description: '무릎이 굳는 것을 예방하는 운동', youtubeId: 'M8Vk_Q5fLnY', duration: '9:30', level: '초급', channel: '강직예방센터' },
        { id: 124, title: '하지 요가 재활', description: '요가 동작을 활용한 하지 재활', youtubeId: 'Q8Lk_V9fYnM', duration: '14:45', level: '초급', channel: '요가재활' },
        { id: 125, title: '보행 장애물 훈련', description: '장애물을 넘는 보행 훈련', youtubeId: 'N9Vk_Q5fLmY', duration: '11:10', level: '중급', channel: '보행훈련센터' },
        { id: 126, title: '하지 근지구력 운동', description: '다리 근육의 지구력을 키우는 운동', youtubeId: 'F8Lk_V9qYnM', duration: '13:35', level: '고급', channel: '근지구력센터' },
        { id: 127, title: '발목 회전 훈련', description: '발목을 다양하게 회전시키는 훈련', youtubeId: 'M9Vk_Q5fLnY', duration: '7:45', level: '초급', channel: '발목재활센터' },
        { id: 128, title: '하지 재활 체조', description: '다리 재활을 위한 체조 프로그램', youtubeId: 'Q9Lk_V8fYmN', duration: '12:00', level: '초급', channel: '재활체조센터' },
        { id: 129, title: '보행 경사로 훈련', description: '경사로에서 걷는 훈련', youtubeId: 'N8Vk_Q5fLnY', duration: '10:55', level: '중급', channel: '보행훈련센터' },
        { id: 130, title: '하지 신경근 운동', description: '신경과 근육을 동시에 자극하는 운동', youtubeId: 'F9Lk_V8qYmN', duration: '11:30', level: '고급', channel: '신경근센터' },
        { id: 131, title: '무릎 재활 종합편', description: '무릎 재활을 위한 종합 프로그램', youtubeId: 'M8Vk_Q5fLnY', duration: '18:15', level: '중급', channel: '종합재활센터' },
        { id: 132, title: '하지 근육 밸런스', description: '다리 근육의 균형을 맞추는 운동', youtubeId: 'Q8Lk_V9fYnM', duration: '10:20', level: '중급', channel: '근육밸런스센터' },
        { id: 133, title: '보행 회전 훈련', description: '방향을 바꾸며 걷는 훈련', youtubeId: 'N9Vk_Q5fLmY', duration: '9:40', level: '중급', channel: '보행훈련센터' },
        { id: 134, title: '하지 체력 증진', description: '다리의 전반적인 체력을 높이는 운동', youtubeId: 'F8Lk_V9qYnM', duration: '14:50', level: '고급', channel: '체력증진센터' },
        { id: 135, title: '발목 유착 방지', description: '발목이 굳는 것을 방지하는 운동', youtubeId: 'M9Vk_Q5fLnY', duration: '8:15', level: '초급', channel: '유착방지센터' },
        { id: 136, title: '하지 관절 가동술', description: '다리 관절을 부드럽게 움직이는 기술', youtubeId: 'Q9Lk_V8fYmN', duration: '11:55', level: '중급', channel: '관절가동센터' },
        { id: 137, title: '보행 안전 훈련', description: '안전하게 걷는 방법 훈련', youtubeId: 'N8Vk_Q5fLnY', duration: '10:30', level: '초급', channel: '안전훈련센터' },
        { id: 138, title: '하지 기능 평가 운동', description: '다리 기능을 평가하며 개선하는 운동', youtubeId: 'F9Lk_V8qYmN', duration: '12:40', level: '중급', channel: '기능평가센터' },
        { id: 139, title: '무릎 수술 후 재활', description: '무릎 수술 후 회복을 위한 재활', youtubeId: 'M8Vk_Q5fLnY', duration: '16:20', level: '중급', channel: '수술후재활센터' },
        { id: 140, title: '하지 종합 재활', description: '하지 전체를 위한 종합 재활 프로그램', youtubeId: 'Q9Lk_V8fYmN', duration: '20:30', level: '중급', channel: '종합재활병원' }
    ],
    speech: [
        // 언어 재활운동 영상 70개
        { id: 141, title: '뇌졸중 언어재활 기초', description: '언어 기능 회복을 위한 기초 훈련', youtubeId: 'TbDHJqOHxBE', duration: '12:40', level: '초급', channel: '대한뇌졸중학회' },
        { id: 142, title: '발음 연습법', description: '명확한 발음을 위한 연습', youtubeId: 'Z4uCb7dXiXU', duration: '10:15', level: '초급', channel: '언어치료센터' },
        { id: 143, title: '혀 운동법', description: '혀의 움직임을 개선하는 운동', youtubeId: 'kH7B3qVLq8M', duration: '8:50', level: '초급', channel: '서울재활병원' },
        { id: 144, title: '입술 운동법', description: '입술 근육을 강화하는 운동', youtubeId: 'nVQ8J5fM9xY', duration: '7:30', level: '초급', channel: '삼성서울병원' },
        { id: 145, title: '호흡 조절 훈련', description: '말하기를 위한 호흡 조절', youtubeId: 'P8Lk_V9fQmY', duration: '9:20', level: '초급', channel: '세브란스병원' },
        { id: 146, title: '음절 연습', description: '음절 단위로 또박또박 말하기', youtubeId: 'N9Vk_Q5fLmY', duration: '11:40', level: '초급', channel: '서울아산병원' },
        { id: 147, title: '단어 따라 말하기', description: '단어를 듣고 따라 말하는 연습', youtubeId: 'F8Lk_V9qYnM', duration: '10:05', level: '초급', channel: '국립재활원' },
        { id: 148, title: '문장 연습', description: '짧은 문장을 말하는 연습', youtubeId: 'M9Vk_Q5fLnY', duration: '12:25', level: '중급', channel: '언어재활센터' },
        { id: 149, title: '삼킴 장애 훈련', description: '안전하게 삼키는 방법 훈련', youtubeId: 'Q8Lk_V9fYnM', duration: '11:10', level: '초급', channel: '연하장애클리닉' },
        { id: 150, title: '목소리 크기 조절', description: '적절한 음량으로 말하기', youtubeId: 'N8Vk_Q5fLnY', duration: '9:35', level: '중급', channel: '음성치료센터' },
        { id: 151, title: '턱 운동법', description: '턱 근육을 풀어주는 운동', youtubeId: 'F9Lk_V8qYmN', duration: '7:50', level: '초급', channel: '구강재활센터' },
        { id: 152, title: '얼굴 표정 운동', description: '얼굴 근육을 활성화하는 운동', youtubeId: 'M8Vk_Q5fLnY', duration: '8:40', level: '초급', channel: '안면재활센터' },
        { id: 153, title: '발성 연습', description: '소리를 내는 기본 연습', youtubeId: 'Q9Lk_V8fYmN', duration: '10:20', level: '초급', channel: '발성훈련센터' },
        { id: 154, title: '유창성 훈련', description: '막힘없이 부드럽게 말하기', youtubeId: 'N9Vk_Q5fLmY', duration: '11:55', level: '중급', channel: '유창성센터' },
        { id: 155, title: '속도 조절 연습', description: '적절한 속도로 말하는 연습', youtubeId: 'F8Lk_V9qYnM', duration: '9:10', level: '중급', channel: '언어치료실' },
        { id: 156, title: '억양 연습', description: '자연스러운 억양으로 말하기', youtubeId: 'M9Vk_Q5fLnY', duration: '10:45', level: '중급', channel: '말하기센터' },
        { id: 157, title: '자음 연습', description: '자음 발음을 정확하게', youtubeId: 'Q8Lk_V9fYnM', duration: '11:30', level: '초급', channel: '발음교정센터' },
        { id: 158, title: '모음 연습', description: '모음을 명확하게 발음하기', youtubeId: 'N8Vk_Q5fLnY', duration: '9:50', level: '초급', channel: '조음훈련센터' },
        { id: 159, title: '이름 대기 훈련', description: '사물과 사람 이름 기억하기', youtubeId: 'F9Lk_V8qYmN', duration: '12:15', level: '중급', channel: '인지언어센터' },
        { id: 160, title: '따라 읽기 연습', description: '글을 보고 따라 읽는 연습', youtubeId: 'M8Vk_Q5fLnY', duration: '10:35', level: '초급', channel: '읽기치료센터' },
        { id: 161, title: '대화 연습', description: '실제 대화 상황 연습', youtubeId: 'Q9Lk_V8fYmN', duration: '13:40', level: '중급', channel: '대화치료센터' },
        { id: 162, title: '듣기 이해 훈련', description: '말을 듣고 이해하는 훈련', youtubeId: 'N9Vk_Q5fLmY', duration: '11:20', level: '중급', channel: '청각언어센터' },
        { id: 163, title: '표현력 향상', description: '생각을 말로 표현하는 연습', youtubeId: 'F8Lk_V9qYnM', duration: '12:50', level: '중급', channel: '표현언어센터' },
        { id: 164, title: '노래 치료', description: '노래를 통한 언어 재활', youtubeId: 'M9Vk_Q5fLnY', duration: '14:10', level: '초급', channel: '음악언어치료' },
        { id: 165, title: '리듬 말하기', description: '리듬에 맞춰 말하는 연습', youtubeId: 'Q8Lk_V9fYnM', duration: '10:00', level: '중급', channel: '리듬치료센터' },
        { id: 166, title: '입 벌리기 운동', description: '입을 크게 벌리는 운동', youtubeId: 'N8Vk_Q5fLnY', duration: '7:25', level: '초급', channel: '구강운동센터' },
        { id: 167, title: '뺨 운동법', description: '뺨 근육을 강화하는 운동', youtubeId: 'F9Lk_V8qYmN', duration: '8:15', level: '초급', channel: '안면근육센터' },
        { id: 168, title: '목 근육 이완', description: '목 주변 근육을 풀어주는 운동', youtubeId: 'M8Vk_Q5fLnY', duration: '9:40', level: '초급', channel: '목재활센터' },
        { id: 169, title: '발화 유도 기법', description: '말을 끌어내는 치료 기법', youtubeId: 'Q9Lk_V8fYmN', duration: '11:05', level: '중급', channel: '발화유도센터' },
        { id: 170, title: '언어 기억력 훈련', description: '단어와 문장 기억하기', youtubeId: 'N9Vk_Q5fLmY', duration: '12:30', level: '중급', channel: '기억력센터' },
        { id: 171, title: '실어증 재활 1단계', description: '실어증 초기 재활 프로그램', youtubeId: 'F8Lk_V9qYnM', duration: '15:20', level: '초급', channel: '실어증센터' },
        { id: 172, title: '실어증 재활 2단계', description: '실어증 중급 재활 프로그램', youtubeId: 'M9Vk_Q5fLnY', duration: '16:40', level: '중급', channel: '실어증센터' },
        { id: 173, title: '실어증 재활 3단계', description: '실어증 고급 재활 프로그램', youtubeId: 'Q8Lk_V9fYnM', duration: '17:55', level: '고급', channel: '실어증센터' },
        { id: 174, title: '구강 감각 자극', description: '입안 감각을 깨우는 훈련', youtubeId: 'N8Vk_Q5fLnY', duration: '8:50', level: '초급', channel: '감각치료센터' },
        { id: 175, title: '침 흘림 관리', description: '침 흘림을 줄이는 훈련', youtubeId: 'F9Lk_V8qYmN', duration: '9:25', level: '초급', channel: '구강관리센터' },
        { id: 176, title: '음식 삼키기 훈련', description: '다양한 음식 안전하게 삼키기', youtubeId: 'M8Vk_Q5fLnY', duration: '13:10', level: '중급', channel: '연하재활센터' },
        { id: 177, title: '목소리 회복 운동', description: '약해진 목소리를 되찾는 운동', youtubeId: 'Q9Lk_V8fYmN', duration: '11:45', level: '중급', channel: '음성재활센터' },
        { id: 178, title: '언어 이해력 향상', description: '말의 의미를 이해하는 훈련', youtubeId: 'N9Vk_Q5fLmY', duration: '12:20', level: '중급', channel: '이해력센터' },
        { id: 179, title: '문법 연습', description: '올바른 문장 구조로 말하기', youtubeId: 'F8Lk_V9qYnM', duration: '10:55', level: '중급', channel: '문법치료센터' },
        { id: 180, title: '호흡 근육 강화', description: '말하기를 위한 호흡근 강화', youtubeId: 'M9Vk_Q5fLnY', duration: '9:30', level: '초급', channel: '호흡치료센터' },
        { id: 181, title: '조음 기관 운동', description: '발음에 관여하는 기관 운동', youtubeId: 'Q8Lk_V9fYnM', duration: '10:40', level: '초급', channel: '조음치료센터' },
        { id: 182, title: '언어 유창성 게임', description: '게임을 통한 언어 연습', youtubeId: 'N8Vk_Q5fLnY', duration: '14:25', level: '중급', channel: '언어게임센터' },
        { id: 183, title: '그림 보고 말하기', description: '그림을 보고 설명하는 연습', youtubeId: 'F9Lk_V8qYmN', duration: '11:30', level: '중급', channel: '시각언어센터' },
        { id: 184, title: '연상 단어 찾기', description: '관련된 단어를 떠올리는 훈련', youtubeId: 'M8Vk_Q5fLnY', duration: '10:15', level: '중급', channel: '인지훈련센터' },
        { id: 185, title: '말 더듬 교정', description: '말 더듬을 줄이는 훈련', youtubeId: 'Q9Lk_V8fYmN', duration: '12:05', level: '중급', channel: '유창성치료센터' },
        { id: 186, title: '목소리 톤 조절', description: '다양한 톤으로 말하는 연습', youtubeId: 'N9Vk_Q5fLmY', duration: '9:45', level: '중급', channel: '음성훈련센터' },
        { id: 187, title: '대화 주고받기', description: '상대방과 대화 주고받는 연습', youtubeId: 'F8Lk_V9qYnM', duration: '13:35', level: '중급', channel: '대화교육센터' },
        { id: 188, title: '질문과 대답 연습', description: '질문을 이해하고 대답하는 훈련', youtubeId: 'M9Vk_Q5fLnY', duration: '11:50', level: '중급', channel: '언어소통센터' },
        { id: 189, title: '이야기 구성하기', description: '이야기를 만들어 말하는 연습', youtubeId: 'Q8Lk_V9fYnM', duration: '14:10', level: '고급', channel: '서사치료센터' },
        { id: 190, title: '전화 대화 연습', description: '전화로 대화하는 상황 연습', youtubeId: 'N8Vk_Q5fLnY', duration: '12:40', level: '중급', channel: '실용언어센터' },
        { id: 191, title: '쇼핑 대화 연습', description: '물건 사는 상황 대화 연습', youtubeId: 'F9Lk_V8qYmN', duration: '11:25', level: '중급', channel: '생활언어센터' },
        { id: 192, title: '병원 대화 연습', description: '병원에서 증상 설명하기', youtubeId: 'M8Vk_Q5fLnY', duration: '10:30', level: '중급', channel: '의료언어센터' },
        { id: 193, title: '식당 주문 연습', description: '음식 주문하는 대화 연습', youtubeId: 'Q9Lk_V8fYmN', duration: '9:50', level: '초급', channel: '일상언어센터' },
        { id: 194, title: '길 물어보기 연습', description: '길을 묻고 답하는 연습', youtubeId: 'N9Vk_Q5fLmY', duration: '10:20', level: '초급', channel: '사회언어센터' },
        { id: 195, title: '감정 표현하기', description: '감정을 말로 표현하는 연습', youtubeId: 'F8Lk_V9qYnM', duration: '11:15', level: '중급', channel: '정서언어센터' },
        { id: 196, title: '의견 말하기', description: '자신의 의견을 표현하는 훈련', youtubeId: 'M9Vk_Q5fLnY', duration: '12:50', level: '중급', channel: '표현훈련센터' },
        { id: 197, title: '설득하기 연습', description: '상대를 설득하는 말하기', youtubeId: 'Q8Lk_V9fYnM', duration: '13:20', level: '고급', channel: '화술센터' },
        { id: 198, title: '사과하기 연습', description: '사과하는 표현 연습', youtubeId: 'N8Vk_Q5fLnY', duration: '9:35', level: '초급', channel: '사회성센터' },
        { id: 199, title: '감사 표현하기', description: '고마움을 전하는 말 연습', youtubeId: 'F9Lk_V8qYmN', duration: '8:40', level: '초급', channel: '예절언어센터' },
        { id: 200, title: '요청하기 연습', description: '부탁하는 말을 하는 연습', youtubeId: 'M8Vk_Q5fLnY', duration: '10:05', level: '초급', channel: '기능언어센터' },
        { id: 201, title: '거절하기 연습', description: '정중하게 거절하는 표현', youtubeId: 'Q9Lk_V8fYmN', duration: '9:20', level: '중급', channel: '화용언어센터' },
        { id: 202, title: '칭찬하기 연습', description: '칭찬하는 말 하는 연습', youtubeId: 'N9Vk_Q5fLmY', duration: '8:55', level: '초급', channel: '긍정언어센터' },
        { id: 203, title: '농담 이해하기', description: '농담과 유머 이해하는 훈련', youtubeId: 'F8Lk_V9qYnM', duration: '11:40', level: '고급', channel: '화용론센터' },
        { id: 204, title: '관용어 배우기', description: '관용적 표현 이해하고 사용하기', youtubeId: 'M9Vk_Q5fLnY', duration: '12:25', level: '고급', channel: '어휘센터' },
        { id: 205, title: '속담 연습', description: '속담의 의미 이해하고 사용하기', youtubeId: 'Q8Lk_V9fYnM', duration: '10:50', level: '고급', channel: '언어문화센터' },
        { id: 206, title: '비유 표현 배우기', description: '비유적 표현 이해하는 훈련', youtubeId: 'N8Vk_Q5fLnY', duration: '11:30', level: '고급', channel: '고급언어센터' },
        { id: 207, title: '언어 재활 게임', description: '게임을 통한 종합 언어 재활', youtubeId: 'F9Lk_V8qYmN', duration: '15:40', level: '중급', channel: '재활게임센터' },
        { id: 208, title: '가족과 대화하기', description: '가족과의 실제 대화 연습', youtubeId: 'M8Vk_Q5fLnY', duration: '13:15', level: '중급', channel: '가족치료센터' },
        { id: 209, title: '언어 재활 마무리', description: '언어 재활 종합 정리', youtubeId: 'Q9Lk_V8fYmN', duration: '14:50', level: '중급', channel: '언어치료센터' },
        { id: 210, title: '언어 종합 재활', description: '언어 전체를 위한 종합 재활 프로그램', youtubeId: 'N9Vk_Q5fLmY', duration: '20:45', level: '중급', channel: '종합재활병원' }
    ]
};
