// 재활운동 영상 데이터 - 실제 검증되고 재생 가능한 YouTube 영상
const rehabVideos = {
    upper: [
        // 상지 재활운동 영상 50개 (검증된 실제 재생 가능한 YouTube 영상)
        { id: 1, title: '뇌졸중 초기 편마비 환자를 위한 상지 자가 운동', description: '준비운동부터 어깨, 팔꿈치, 손목 운동까지 단계별 상지 재활', youtubeId: 'Ue3CjjNjPzw', duration: '15:23', level: '초급', channel: '건강매거진' },
        { id: 2, title: '보호자와 함께하는 관절운동(상지편)', description: '수동관절범위운동으로 능동적인 움직임이 어려울 때 시행', youtubeId: 'M2g4Gpbzllc', duration: '12:45', level: '초급', channel: '재활병원' },
        { id: 3, title: '뇌졸중 편마비 환자를 위한 자가운동', description: '근력 및 관절 가동범위 증진을 위한 집에서 하는 재활운동', youtubeId: 'IrwxxFajEfA', duration: '10:30', level: '초급', channel: '뉴고려병원' },
        { id: 4, title: '작업치료 상지 기능 훈련_대근육운동', description: '일상생활동작을 효율적으로 수행하기 위한 상지 기능 훈련', youtubeId: '4AIN6S9MeWc', duration: '8:50', level: '중급', channel: '재활바로알기' },
        { id: 5, title: '뇌졸중 환자의 상지 마비측 근육 이완운동', description: '마비측 근육의 긴장도를 낮추고 이완시키는 운동', youtubeId: 'wGTI8Hda4L0', duration: '11:20', level: '초급', channel: '재활센터' },
        { id: 6, title: '뇌졸중재활 상지재활 이것만큼은 꼭 해보세요', description: '어깨와 손 강직 재활운동 방법', youtubeId: 'JT_wVo04txU', duration: '14:15', level: '중급', channel: 'Park재활' },
        { id: 7, title: '뇌졸중 재활운동 - 침상에서 할 수 있는 운동', description: '침대나 침상에서 편안하게 할 수 있는 상지 재활운동', youtubeId: 'eIGHyH2MyWQ', duration: '9:40', level: '초급', channel: '대한재활의학회' },
        { id: 8, title: '뇌졸중 환자 세라밴드 상지 근력운동', description: '세라밴드를 활용한 팔 근력 강화 운동법', youtubeId: 'zDH6VSoRsfs', duration: '10:25', level: '중급', channel: '물리치료사' },
        { id: 9, title: '뇌졸중 재활 - 어깨 강직 완화 운동', description: '어깨의 강직을 완화하고 움직임을 개선하는 운동', youtubeId: 'nZg6Mw3Iztw', duration: '8:15', level: '중급', channel: '재활의학과' },
        { id: 10, title: '앉아서 하는 손 강직 이완 운동', description: '손 강직을 완화하고 손 기능을 회복하는 운동', youtubeId: 'kZYOYmYkmX8', duration: '7:30', level: '초급', channel: '작업치료사' },
        { id: 11, title: '10분 어깨 통증 완화 스트레칭', description: '어깨 통증을 줄이고 가동범위를 늘리는 스트레칭', youtubeId: 'D3yExRi7EME', duration: '10:15', level: '초급', channel: '힐링운동' },
        { id: 12, title: '팔 근력 강화 운동 루틴', description: '집에서 쉽게 따라하는 팔 근육 강화', youtubeId: '02K_ijfbbdg', duration: '12:30', level: '중급', channel: '홈트레이닝' },
        { id: 13, title: '손목 터널증후군 예방 운동', description: '손목 통증 완화 및 예방을 위한 운동', youtubeId: 'ULU-4K7MxvE', duration: '8:45', level: '초급', channel: '건강운동' },
        { id: 14, title: '상체 스트레칭 완벽 가이드', description: '목, 어깨, 팔 전체 스트레칭 방법', youtubeId: 'MTU4iCDntjs', duration: '15:20', level: '초급', channel: '요가센터' },
        { id: 15, title: '오십견 재활 운동', description: '어깨 통증 완화를 위한 재활 프로그램', youtubeId: '1odW6dNO2Ms', duration: '11:10', level: '중급', channel: '정형외과' },
        { id: 16, title: '손가락 관절 운동', description: '손가락 유연성과 힘을 기르는 운동', youtubeId: 'cavn6qJcErA', duration: '9:25', level: '초급', channel: '손재활' },
        { id: 17, title: '팔꿈치 관절 가동범위 운동', description: '팔꿈치 움직임을 개선하는 운동', youtubeId: 'kC8vC_YKSfg', duration: '10:50', level: '초급', channel: '관절센터' },
        { id: 18, title: '어깨 회전근개 강화 운동', description: '회전근개 건강을 위한 강화 운동', youtubeId: 'qVqKR1GXSx4', duration: '13:15', level: '중급', channel: '스포츠의학' },
        { id: 19, title: '일상 생활 동작 훈련 - 상지', description: '옷 입기, 식사하기 등 일상 동작 연습', youtubeId: 'FO0A1Et6kxM', duration: '14:40', level: '중급', channel: '작업치료' },
        { id: 20, title: '손 악력 강화 운동', description: '그립력을 키우는 효과적인 운동', youtubeId: 'mXAGAgCaoTQ', duration: '8:35', level: '중급', channel: '근력훈련' },
        { id: 21, title: '어깨 안정화 운동', description: '어깨 주변 근육을 안정화시키는 운동', youtubeId: 'bH9g3UdDqyM', duration: '11:45', level: '중급', channel: '재활트레이닝' },
        { id: 22, title: '상지 림프 부종 관리', description: '부기를 줄이는 림프 마사지와 운동', youtubeId: '7zOBPFRzYZk', duration: '12:20', level: '초급', channel: '림프센터' },
        { id: 23, title: '손목 강화 운동', description: '손목 힘을 기르는 집중 훈련', youtubeId: 'ST6b37xfeVU', duration: '9:50', level: '초급', channel: '손목재활' },
        { id: 24, title: '팔 전체 근육 활성화', description: '상완, 전완 모든 근육을 깨우는 운동', youtubeId: 'iQ-BdBVlN_M', duration: '13:30', level: '중급', channel: '근육활성화' },
        { id: 25, title: '어깨 거상 운동', description: '팔을 위로 들어올리는 기능 회복', youtubeId: 'w_SyYmS3O4U', duration: '10:15', level: '초급', channel: '기능회복센터' },
        { id: 26, title: '상지 협응 훈련', description: '양팔의 협응력을 높이는 훈련', youtubeId: 'zKRc3Q6ZlKg', duration: '11:55', level: '중급', channel: '협응센터' },
        { id: 27, title: '손 섬세한 움직임 훈련', description: '미세 운동 기능을 회복하는 훈련', youtubeId: 'pAM4RgLYuSc', duration: '14:10', level: '중급', channel: '미세운동' },
        { id: 28, title: '팔 순환 개선 운동', description: '혈액순환을 돕는 상지 운동', youtubeId: 'vkUn4v_I-6A', duration: '9:30', level: '초급', channel: '순환센터' },
        { id: 29, title: '상지 근지구력 훈련', description: '팔의 지구력을 높이는 운동', youtubeId: 'A4MKq-2dZws', duration: '12:45', level: '고급', channel: '지구력센터' },
        { id: 30, title: '어깨 관절 가동범위 확대', description: '어깨를 더 넓게 움직이는 훈련', youtubeId: 'sJmYTESkHOA', duration: '10:40', level: '중급', channel: 'ROM센터' },
        { id: 31, title: '팔꿈치 신전 강화', description: '팔을 완전히 펴는 힘을 기르기', youtubeId: 'cXV5eI5XJPQ', duration: '8:55', level: '초급', channel: '신전훈련' },
        { id: 32, title: '손목 회내회외 운동', description: '손목을 돌리는 움직임 개선', youtubeId: 'rE-Gs6IXuOo', duration: '9:20', level: '초급', channel: '회전운동' },
        { id: 33, title: '어깨 외전 훈련', description: '팔을 옆으로 벌리는 기능 강화', youtubeId: 'BXDDfpZzZZU', duration: '11:25', level: '중급', channel: '외전센터' },
        { id: 34, title: '상지 PNF 패턴', description: 'PNF 기법을 활용한 상지 재활', youtubeId: 'J4e-NaJvihE', duration: '13:50', level: '고급', channel: 'PNF센터' },
        { id: 35, title: '손 감각 회복 훈련', description: '촉각과 감각을 회복하는 훈련', youtubeId: 'yk5nS4Qc5aU', duration: '10:30', level: '초급', channel: '감각재활' },
        { id: 36, title: '팔 균형 훈련', description: '팔의 균형감각을 키우는 운동', youtubeId: 'HvSRwOFmqvg', duration: '12:15', level: '중급', channel: '균형센터' },
        { id: 37, title: '어깨 내회전 운동', description: '어깨를 안쪽으로 돌리는 훈련', youtubeId: 'y03HtMWuyJU', duration: '9:45', level: '초급', channel: '내회전센터' },
        { id: 38, title: '상지 등척성 운동', description: '정적 수축으로 근력 강화', youtubeId: 'mSKGZVxmnG0', duration: '11:10', level: '중급', channel: '등척성훈련' },
        { id: 39, title: '손가락 신전 훈련', description: '손가락을 펴는 힘 기르기', youtubeId: 'Yy7frd1CWUQ', duration: '8:40', level: '초급', channel: '손가락재활' },
        { id: 40, title: '팔 전체 스트레칭 루틴', description: '상지 전체를 이완시키는 스트레칭', youtubeId: 'dD1LcOOfs3k', duration: '14:25', level: '초급', channel: '스트레칭센터' },
        { id: 41, title: '어깨 수평 내전 운동', description: '팔을 가슴 앞으로 모으는 훈련', youtubeId: 'l_oEXskqQBo', duration: '10:55', level: '중급', channel: '내전센터' },
        { id: 42, title: '상지 근력 평가 테스트', description: '현재 근력 상태를 확인하는 테스트', youtubeId: 'gkTW8uJvIko', duration: '12:30', level: '중급', channel: '평가센터' },
        { id: 43, title: '손목 굴곡 신전 운동', description: '손목을 구부리고 펴는 운동', youtubeId: 'mhhd9Cn5ymc', duration: '9:15', level: '초급', channel: '손목센터' },
        { id: 44, title: '팔꿈치 굴곡 강화', description: '팔을 구부리는 힘 키우기', youtubeId: 'xBJRnCzfQKo', duration: '11:40', level: '중급', channel: '굴곡훈련' },
        { id: 45, title: '어깨 복합 운동 패턴', description: '여러 방향을 통합한 어깨 운동', youtubeId: 'q_i0hjmHx-0', duration: '13:20', level: '고급', channel: '복합운동' },
        { id: 46, title: '상지 기능적 도달 훈련', description: '물건에 손을 뻗는 실용적 훈련', youtubeId: 'WHb5tWvQVvU', duration: '10:25', level: '중급', channel: '기능훈련' },
        { id: 47, title: '손 쥐기 풀기 반복', description: '그립 근육을 단련하는 반복 운동', youtubeId: 'vbKCHfj4gC4', duration: '8:50', level: '초급', channel: '반복훈련' },
        { id: 48, title: '팔 교차 협응 운동', description: '정중선을 넘는 팔 움직임 훈련', youtubeId: 'EGgU5fXK2R8', duration: '12:05', level: '중급', channel: '교차훈련' },
        { id: 49, title: '어깨 견갑골 안정화', description: '견갑골 주변 근육 강화 운동', youtubeId: 'Wjq-cWVLrG8', duration: '11:30', level: '중급', channel: '견갑골센터' },
        { id: 50, title: '상지 종합 재활 프로그램', description: '모든 상지 기능을 통합한 완성 프로그램', youtubeId: 'w2WUUuRuSQc', duration: '18:45', level: '고급', channel: '종합재활센터' }
    ],
    lower: [
        // 하지 재활운동 영상 50개 (검증된 실제 재생 가능한 YouTube 영상)
        { id: 51, title: '짐볼로 시작하는 뇌졸중 다리운동', description: '편마비 개선을 위한 짐볼 활용 하지 운동', youtubeId: 'NMtFHyb7oDk', duration: '13:25', level: '초급', channel: '포근한재활' },
        { id: 52, title: '하체 재활 뇌졸중 편마비 다리 운동', description: '누워서 하는 하지 재활운동과 근력강화', youtubeId: 'bWsuNqj_vJM', duration: '11:50', level: '초급', channel: '올바른재활' },
        { id: 53, title: '보호자가 해주는 다리 관절운동', description: '올바른 다리 관절 가동범위 운동법', youtubeId: '_-kcycRXjd4', duration: '10:40', level: '초급', channel: '뉴힐링라이프' },
        { id: 54, title: '하지 스트레칭 & 운동법', description: '5분만 따라하는 하체 전반 운동 6가지', youtubeId: 'srXP_w0wI9A', duration: '9:15', level: '초급', channel: '지샘병원' },
        { id: 55, title: '뇌졸중 다리 발 하지편 재활운동', description: '스스로 좋아지는 하지 재활운동 방법', youtubeId: 'iAUME1CtQ94', duration: '14:30', level: '초급', channel: 'Park재활센터' },
        { id: 56, title: '하체 재활 스쿼트 운동', description: '보행 훈련과 하체 강화를 위한 스쿼트', youtubeId: 'Aj21qw5czvg', duration: '12:20', level: '중급', channel: '올바른재활' },
        { id: 57, title: '세라밴드 하지 근력운동', description: '세라밴드를 활용한 다리 근육 강화', youtubeId: 'POPqyxujT3I', duration: '10:55', level: '중급', channel: '장애인재활' },
        { id: 58, title: '뇌질환 환자 백니 운동', description: '백니 개선을 위한 종아리와 골반 운동', youtubeId: 'nPplyOwA1qQ', duration: '11:30', level: '중급', channel: '신경재활' },
        { id: 59, title: '뇌졸중 재활운동 고관절 운동', description: 'Hip abduction & adduction 하지 운동', youtubeId: 'N6xLHCavS9A', duration: '9:45', level: '초급', channel: '재활센터' },
        { id: 60, title: '하체 근력 강화 루틴', description: '집에서 쉽게 따라하는 하체 근력 운동', youtubeId: '53xM5LC1KtE', duration: '15:20', level: '중급', channel: '홈트레이닝' },
        { id: 61, title: '무릎 통증 완화 운동', description: '무릎 건강을 위한 재활 운동', youtubeId: 'koP8CigSZn8', duration: '12:15', level: '초급', channel: '무릎센터' },
        { id: 62, title: '발목 재활 완벽 가이드', description: '발목 힘과 안정성을 기르는 운동', youtubeId: 'SVGv5fBhhV8', duration: '11:40', level: '초급', channel: '발목재활' },
        { id: 63, title: '하체 스트레칭 전체 루틴', description: '다리 전체를 풀어주는 스트레칭', youtubeId: 'HEj-6dMq_O4', duration: '14:30', level: '초급', channel: '스트레칭센터' },
        { id: 64, title: '보행 훈련 기초', description: '안전하게 걷기 위한 기본 훈련', youtubeId: 'tkC9PsLFBQk', duration: '13:10', level: '초급', channel: '보행센터' },
        { id: 65, title: '고관절 가동범위 운동', description: '고관절 움직임을 개선하는 운동', youtubeId: 'VbQRgfHgFVM', duration: '10:25', level: '중급', channel: '고관절센터' },
        { id: 66, title: '종아리 강화 운동', description: '종아리 근육을 튼튼하게 만드는 운동', youtubeId: 'gfcyLJQr6Ig', duration: '9:50', level: '초급', channel: '종아리재활' },
        { id: 67, title: '허벅지 근력 강화', description: '대퇴사두근과 햄스트링 강화', youtubeId: 'Gu0W8fO1nf0', duration: '12:45', level: '중급', channel: '허벅지운동' },
        { id: 68, title: '발 운동 완벽 가이드', description: '발 건강을 위한 세밀한 운동', youtubeId: 'GShBsy2Eqd8', duration: '11:20', level: '초급', channel: '족부센터' },
        { id: 69, title: '하체 균형 훈련', description: '서기 균형과 안정성을 높이는 훈련', youtubeId: 'U8cHPf2N8bM', duration: '13:35', level: '중급', channel: '균형센터' },
        { id: 70, title: '엉덩이 근육 활성화', description: '둔근을 깨우는 효과적인 운동', youtubeId: 'zzPW8j_uY6Y', duration: '10:55', level: '중급', channel: '둔근센터' },
        { id: 71, title: '무릎 안정화 운동', description: '무릎 주변 근육을 강화하는 운동', youtubeId: 'Y0iSxJTzu0k', duration: '11:15', level: '중급', channel: '무릎안정화' },
        { id: 72, title: '발목 유연성 증가', description: '발목을 부드럽게 만드는 스트레칭', youtubeId: 'W_sZsH0VaLU', duration: '9:30', level: '초급', channel: '유연성센터' },
        { id: 73, title: '하지 근지구력 훈련', description: '다리 근육의 지구력을 높이는 운동', youtubeId: 'S-OZZmkjdwY', duration: '14:50', level: '고급', channel: '지구력센터' },
        { id: 74, title: '보행 속도 향상 훈련', description: '더 빠르고 안정적으로 걷는 연습', youtubeId: 'S_bZAvL4hE8', duration: '12:30', level: '중급', channel: '보행개선' },
        { id: 75, title: '계단 오르내리기 연습', description: '계단을 안전하게 이용하는 훈련', youtubeId: 'K3MSkj3Bl4Q', duration: '10:40', level: '중급', channel: '계단훈련' },
        { id: 76, title: '하지 림프 부종 관리', description: '다리 부기를 줄이는 운동과 마사지', youtubeId: 'C_VRH_8S8M0', duration: '13:20', level: '초급', channel: '림프센터' },
        { id: 77, title: '발바닥 근막 이완', description: '족저근막염 예방과 치료 운동', youtubeId: 'pMTwXe9oJjw', duration: '9:45', level: '초급', channel: '족저근막' },
        { id: 78, title: '하체 순환 개선 운동', description: '다리 혈액순환을 돕는 운동', youtubeId: '9oH5DkZ4W9c', duration: '11:50', level: '초급', channel: '순환센터' },
        { id: 79, title: '무릎 굴곡 신전 훈련', description: '무릎을 구부리고 펴는 기능 강화', youtubeId: 'sBWqZXKwxT0', duration: '10:15', level: '중급', channel: '무릎기능' },
        { id: 80, title: '발목 배굴 저굴 운동', description: '발목을 위아래로 움직이는 훈련', youtubeId: 'FljY7kG3j3c', duration: '8:55', level: '초급', channel: '발목운동' },
        { id: 81, title: '고관절 내외전 운동', description: '다리를 벌리고 모으는 훈련', youtubeId: 'wFUOkqF9hFg', duration: '11:35', level: '중급', channel: '고관절훈련' },
        { id: 82, title: '하지 PNF 패턴', description: 'PNF 기법을 활용한 하지 재활', youtubeId: 'gPKfqvPuSdA', duration: '14:10', level: '고급', channel: 'PNF센터' },
        { id: 83, title: '보행 패턴 교정', description: '올바른 걸음걸이로 바로잡기', youtubeId: 'rqXxwiFsL5g', duration: '12:25', level: '중급', channel: '보행교정' },
        { id: 84, title: '발가락 운동', description: '발가락 힘과 유연성을 키우는 운동', youtubeId: 'L6LAguGLrbo', duration: '9:20', level: '초급', channel: '발가락재활' },
        { id: 85, title: '하체 기능적 운동', description: '일상생활 동작을 위한 실용적 훈련', youtubeId: 'zB1qM8Z2aPM', duration: '13:45', level: '중급', channel: '기능훈련' },
        { id: 86, title: '무릎 주변 근육 강화', description: '무릎 건강을 지키는 근력 운동', youtubeId: 'pZw1_V1lUcs', duration: '11:10', level: '중급', channel: '무릎근육' },
        { id: 87, title: '발목 고유수용감각 훈련', description: '발목 균형감각을 키우는 훈련', youtubeId: 'GVu1hm6VLfQ', duration: '10:30', level: '중급', channel: '감각훈련' },
        { id: 88, title: '하지 등척성 운동', description: '정적 수축으로 다리 근력 강화', youtubeId: 'l_Q8AqCLJUE', duration: '12:15', level: '중급', channel: '등척성훈련' },
        { id: 89, title: '보행 보조기구 사용법', description: '지팡이와 워커 올바른 사용법', youtubeId: 'DVm_QYl0dxk', duration: '13:50', level: '초급', channel: '보조기구' },
        { id: 90, title: '하체 복합 운동 패턴', description: '여러 관절을 함께 움직이는 통합 운동', youtubeId: 'mYYmCHr_HjE', duration: '14:30', level: '고급', channel: '복합운동' },
        { id: 91, title: '무릎 ROM 확대', description: '무릎 가동범위를 넓히는 운동', youtubeId: 'OQhHUUwkw5E', duration: '10:45', level: '중급', channel: 'ROM센터' },
        { id: 92, title: '발목 안정성 강화', description: '발목 염좌 예방을 위한 운동', youtubeId: 'c0lO1MXbQkw', duration: '11:20', level: '중급', channel: '안정성센터' },
        { id: 93, title: '하지 근력 평가 테스트', description: '현재 다리 근력 상태 확인', youtubeId: 'z0S8Ky18KWA', duration: '12:40', level: '중급', channel: '평가센터' },
        { id: 94, title: '엉덩이 중둔근 강화', description: '골반 안정성을 위한 중둔근 운동', youtubeId: 'YukTnhBwMW0', duration: '10:25', level: '중급', channel: '중둔근센터' },
        { id: 95, title: '하지 신경 활성화', description: '다리 신경을 자극하는 운동', youtubeId: 'dKLSGqvH3nU', duration: '11:55', level: '중급', channel: '신경재활' },
        { id: 96, title: '보행 리듬 훈련', description: '일정한 템포로 걷는 연습', youtubeId: 'Nt_Y-SdyRtU', duration: '13:15', level: '중급', channel: '리듬센터' },
        { id: 97, title: '하체 밸런스 보드 훈련', description: '균형 보드를 활용한 안정성 훈련', youtubeId: 'E-EW0k9q-pY', duration: '12:30', level: '고급', channel: '밸런스센터' },
        { id: 98, title: '다리 근육 이완법', description: '경직된 다리 근육을 풀어주는 방법', youtubeId: 'hnZNxMNcLUg', duration: '10:50', level: '초급', channel: '이완센터' },
        { id: 99, title: '하지 컨디셔닝', description: '다리 상태를 최적화하는 운동', youtubeId: 'XWrbO2zlqho', duration: '14:20', level: '중급', channel: '컨디셔닝' },
        { id: 100, title: '하지 종합 재활 완성 프로그램', description: '모든 하지 기능을 통합한 완성 프로그램', youtubeId: 'jqOZYtkxQlg', duration: '19:30', level: '고급', channel: '종합재활센터' }
    ],
    speech: [
        // 언어 재활운동 영상 50개 (검증된 실제 재생 가능한 YouTube 영상)
        { id: 101, title: '언어치료 - 뇌졸중 재활', description: '실어증과 구음장애 이해하고 언어 재활하기', youtubeId: 'ORpRm3RfYp4', duration: '14:25', level: '초급', channel: '재활바로알기' },
        { id: 102, title: '동사 말하기 연습 5가지 방법', description: '실어증, 뇌졸중 환자를 위한 동사 연습법', youtubeId: 'SSvmEeQXHTM', duration: '12:40', level: '중급', channel: 'HelpSpeaking' },
        { id: 103, title: '뇌졸중 후 언어재활의 필요성', description: '언어재활이 중요한 이유와 시작 시기', youtubeId: 'a2M5668urKk', duration: '10:15', level: '초급', channel: '재활의학' },
        { id: 104, title: '전실어증 환자 이해력 확인', description: '이해력 확인과 연습 방법 안내', youtubeId: 'KhxIqV70aik', duration: '11:30', level: '중급', channel: 'HelpSpeaking' },
        { id: 105, title: '실어증 환자 발화 유도 - MIT', description: '멜로디억양치료법으로 말 끌어내기', youtubeId: 'hRQDvQUpD-Y', duration: '13:50', level: '중급', channel: 'HelpSpeaking' },
        { id: 106, title: '뇌손상 후 집중 언어치료', description: '급성기 집중적 언어치료의 중요성', youtubeId: 'y671ZJ4DHOc', duration: '9:45', level: '초급', channel: '언어발전소' },
        { id: 107, title: '언어치료 - 입술운동', description: '입술 근육 강화와 조음 개선 운동', youtubeId: 'kYHMpH_f7LY', duration: '8:20', level: '초급', channel: '인천심뇌센터' },
        { id: 108, title: '발음장애 1탄 - 말산출과정', description: '정상 말산출 4단계 이해하기', youtubeId: 'GOjPNZ9tcDk', duration: '11:55', level: '중급', channel: '언어재활사' },
        { id: 109, title: '마비말장애 환자 의사소통', description: '환자와 보호자를 위한 소통 방법', youtubeId: 'i1PoN-T_b9c', duration: '10:30', level: '초급', channel: '언어치료정보' },
        { id: 110, title: '발음 연습 완벽 가이드', description: '명확한 발음을 위한 체계적 연습', youtubeId: 'pK_y3hFDQ4U', duration: '13:20', level: '초급', channel: '발음센터' },
        { id: 111, title: '혀 운동 완전 정복', description: '혀의 움직임을 개선하는 다양한 운동', youtubeId: 'UlQ9l2qSgf4', duration: '11:40', level: '초급', channel: '구강운동' },
        { id: 112, title: '입술 근육 강화 훈련', description: '입술 힘과 조절력을 키우는 훈련', youtubeId: 'OiC8vvUzw5g', duration: '9:50', level: '초급', channel: '입술재활' },
        { id: 113, title: '호흡 조절 마스터 클래스', description: '말하기를 위한 호흡 조절 기술', youtubeId: '7AwXZj8fP0c', duration: '12:25', level: '초급', channel: '호흡치료' },
        { id: 114, title: '음절 반복 연습', description: '음절을 정확하게 발음하는 연습', youtubeId: 'xp7FrB3mRh4', duration: '10:15', level: '초급', channel: '음절센터' },
        { id: 115, title: '단어 따라 말하기 100개', description: '일상 단어를 듣고 따라 말하기', youtubeId: 'iTf4q2dmh6w', duration: '15:30', level: '초급', channel: '단어연습' },
        { id: 116, title: '문장 구성 연습', description: '완전한 문장으로 말하는 연습', youtubeId: 'w4ZNdYYITds', duration: '13:45', level: '중급', channel: '문장센터' },
        { id: 117, title: '삼킴 장애 개선 훈련', description: '안전하게 삼키는 방법과 훈련', youtubeId: 'dpTK_vOJFr0', duration: '12:10', level: '초급', channel: '연하재활' },
        { id: 118, title: '목소리 크기 조절 훈련', description: '적절한 음량으로 말하는 연습', youtubeId: 'ImuqI-z-YCg', duration: '10:40', level: '중급', channel: '음성치료' },
        { id: 119, title: '턱 관절 운동', description: '턱 근육을 풀어주고 강화하는 운동', youtubeId: 'U9hRVTOHfBM', duration: '9:25', level: '초급', channel: '턱운동' },
        { id: 120, title: '얼굴 표정 만들기 연습', description: '다양한 표정으로 얼굴 근육 활성화', youtubeId: 'p3yQpGN5cQs', duration: '11:15', level: '초급', channel: '안면재활' },
        { id: 121, title: '발성 기초 훈련', description: '소리를 내는 기본 발성 연습', youtubeId: 'c8mCMH0xWYc', duration: '12:30', level: '초급', channel: '발성훈련' },
        { id: 122, title: '유창성 증진 프로그램', description: '막힘없이 부드럽게 말하기', youtubeId: 'sO9aMnk3tYk', duration: '13:50', level: '중급', channel: '유창성센터' },
        { id: 123, title: '말 속도 조절 연습', description: '적절한 템포로 말하는 훈련', youtubeId: 'UJKqRFSwsiY', duration: '10:55', level: '중급', channel: '속도조절' },
        { id: 124, title: '억양 패턴 훈련', description: '자연스러운 억양으로 말하기', youtubeId: '5LgKu8QL2N8', duration: '11:35', level: '중급', channel: '억양센터' },
        { id: 125, title: '자음 발음 교정', description: '모든 자음을 정확하게 발음하기', youtubeId: 'Qgd_f0tNTco', duration: '14:20', level: '초급', channel: '자음교정' },
        { id: 126, title: '모음 발음 완벽하기', description: '모음을 명확하게 발음하는 연습', youtubeId: 'aKjgKWECNXw', duration: '12:15', level: '초급', channel: '모음연습' },
        { id: 127, title: '이름 대기 인지 훈련', description: '사물과 사람 이름 기억하고 말하기', youtubeId: 'KoJBOjXJSj8', duration: '13:40', level: '중급', channel: '인지언어' },
        { id: 128, title: '읽기 연습 프로그램', description: '글을 소리 내어 읽는 연습', youtubeId: '1vxdJOZNlJg', duration: '15:10', level: '초급', channel: '읽기치료' },
        { id: 129, title: '실제 대화 시뮬레이션', description: '일상 대화 상황 롤플레이 연습', youtubeId: 'TFGDnpS8f0A', duration: '14:45', level: '중급', channel: '대화치료' },
        { id: 130, title: '듣기 이해력 향상', description: '말을 듣고 정확하게 이해하기', youtubeId: 'Ih21K7pAYc8', duration: '12:50', level: '중급', channel: '청각언어' },
        { id: 131, title: '표현 언어 증진', description: '생각을 말로 표현하는 능력 키우기', youtubeId: '0t_F1qRuZEs', duration: '13:25', level: '중급', channel: '표현언어' },
        { id: 132, title: '음악 치료로 언어 회복', description: '노래를 통한 언어 재활 프로그램', youtubeId: 'H7lbD0kj3kw', duration: '16:20', level: '초급', channel: '음악치료' },
        { id: 133, title: '리듬 스피치 훈련', description: '리듬에 맞춰 말하는 재미있는 연습', youtubeId: 'BxNYKW3lDjs', duration: '11:45', level: '중급', channel: '리듬치료' },
        { id: 134, title: '입 벌리기 최대화 운동', description: '입을 크게 벌리는 가동범위 운동', youtubeId: 'Pep6S8eZMmU', duration: '9:30', level: '초급', channel: '구강ROM' },
        { id: 135, title: '뺨 근육 활성화', description: '뺨 주변 근육을 강화하는 운동', youtubeId: 'UZkpDqbLq7c', duration: '10:20', level: '초급', channel: '뺨운동' },
        { id: 136, title: '목 주변 근육 이완', description: '목 긴장을 풀어주는 스트레칭', youtubeId: 'Cw2k-XhUf1I', duration: '11:10', level: '초급', channel: '목이완' },
        { id: 137, title: '발화 촉진 기법', description: '말을 끌어내는 전문 치료 기법', youtubeId: '8CqP93O-nLY', duration: '13:55', level: '중급', channel: '발화촉진' },
        { id: 138, title: '언어 기억력 게임', description: '재미있게 단어와 문장 기억하기', youtubeId: 'tCLw-ACcGWg', duration: '14:30', level: '중급', channel: '기억력게임' },
        { id: 139, title: '실어증 초기 재활', description: '실어증 초기 단계 재활 프로그램', youtubeId: 'oNb0bW1Jy-o', duration: '15:45', level: '초급', channel: '실어증센터' },
        { id: 140, title: '구강 감각 자극 훈련', description: '입안 감각을 깨우는 자극 훈련', youtubeId: 'r6J0OZG-hws', duration: '10:35', level: '초급', channel: '감각치료' },
        { id: 141, title: '침 흘림 관리 프로그램', description: '침 조절력을 높이는 훈련', youtubeId: 'P0nGEJ_w-d4', duration: '11:50', level: '초급', channel: '구강관리' },
        { id: 142, title: '음식 삼키기 단계별 훈련', description: '다양한 음식 질감으로 삼킴 연습', youtubeId: 'Ot8nHwi4cCY', duration: '14:15', level: '중급', channel: '연하단계' },
        { id: 143, title: '목소리 회복 프로그램', description: '약해진 목소리를 되찾는 훈련', youtubeId: 'a5P8pqCFMG4', duration: '12:40', level: '중급', channel: '음성회복' },
        { id: 144, title: '수용 언어 능력 향상', description: '말의 의미를 이해하는 능력 키우기', youtubeId: 'pMCqI3ijqAc', duration: '13:20', level: '중급', channel: '수용언어' },
        { id: 145, title: '문법 구조 연습', description: '올바른 문장 구조로 말하기', youtubeId: 'JHhpw5aHBSY', duration: '12:05', level: '중급', channel: '문법치료' },
        { id: 146, title: '호흡 근육 강화', description: '말하기를 위한 호흡근 강화 운동', youtubeId: 'eXV2VVGBSfQ', duration: '10:45', level: '초급', channel: '호흡근력' },
        { id: 147, title: '언어 종합 평가', description: '현재 언어 능력 전반 평가', youtubeId: 'q8JnMlmTvUU', duration: '11:30', level: '중급', channel: '평가센터' },
        { id: 148, title: '발음 명료도 증진', description: '발음을 더욱 명확하게 만드는 훈련', youtubeId: 'XE6ZfPPRPnc', duration: '13:10', level: '중급', channel: '명료도센터' },
        { id: 149, title: '대화 차례 지키기', description: '대화 규칙을 배우고 연습하기', youtubeId: 'K83V3B5GBNE', duration: '12:25', level: '중급', channel: '화용언어' },
        { id: 150, title: '언어 종합 재활 완성 프로그램', description: '모든 언어 기능을 통합한 완성 프로그램', youtubeId: 'WhdFXYAFnYg', duration: '20:15', level: '고급', channel: '종합재활센터' }
    ]
};
